React-Redux Bookstore - Second Milestone
Psiale/react-redux-bookstore pull request #2
Opened 2021-01-22 23:01 UTC by Rhelli

# 📚 React-Redux BookStore - Second Milestone
Hi there,

Following the finish of the first milestone, we have completed the following steps for the second milestone:
 - Prepared the file structure as specified by the Microverse guidelines
 - Implemented the `App` component which contains the `BooksList` and `BooksForm` components
 - Implemented the `BooksList` component which is connected to the Redux store and displays the initially defined books.
 -  Implemented the `Book` component which builds individual `Books` and returns them as single row objects
 - Implemented the `BookForm` component which includes all the required fields to enter a title and choose a category for a new book as well as submit it to the redux store.
 - Defined all the Redux actions and reducers
 - Initialised the redux store with an initial state.

Let us know if there are any issues with this over slack.

All the best,

Alexis and Rory

2021-01-23 07:34 UTC, wathigo requested changes
## Changes Required :o: 
Great job on this milestone.
Let's make a few changes before we move on. See the comments :point_down: 

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2021-01-23 07:34 UTC, wathigo commented on src/containers/App.js
> +      <BooksList Books={Book} />
We don't need to pass the Book component as the value of Books prop since we are already accessing books from the redux store in the BookList component.

2021-01-23 07:34 UTC, wathigo commented on src/containers/App.js
> +function App() {
The App component should be placed in `src/components` since it is a representational component (has no access to the store or the app state).
Let's make use of es6 arrow syntax.

2021-01-23 07:34 UTC, wathigo commented on src/components/BooksForm.js
> +          <option value={categories[6]}>{categories[6]}</option>
Let's avoid code repetition by replacing this with:
```js
{
     categories.map(category => <option key={category}>{category}</option>)
}
```

2021-01-25 20:55 UTC, Rhelli commented
# 📚 React-Redux Bookstore - Milestone 2
Hi there,

As proposed by @wathigo above, we have made the following changes to our project:

 - Removed the passing the `Book` component as it is already passed at the highest level via the redux store
 - Moved `App.js` to the `components` folder from the `containers` folder
 - Modified `BookForm.js` to use `map` to reduce the length of our JSX.

Thanks in advance,

Alexis and Rory

2021-01-25 22:01 UTC, Torres-ssf approved these changes
### Milestone approved :+1: 
Hi team :hand: 
Great job implementing the requested changes

- [ ] Bookform component will be connected with Redux on the next milestone, therefore, is considered a Container component. We need to move it to the `src/containers` directory. 

Happy coding :computer: 
**Sergio Torres**

2021-01-25 22:16 UTC, closed without merging